"""sync model to EGN no end_at

Revision ID: 14dde6799703
Revises: 7a7f9fa4a7c4
Create Date: 2026-02-28 11:34:39.461513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14dde6799703'
down_revision: Union[str, Sequence[str], None] = '7a7f9fa4a7c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('EGN', sa.String(length=10), nullable=False))
    op.drop_column('appointments', 'end_at')
    op.alter_column('doctors', 'location',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctors', 'location',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.add_column('appointments', sa.Column('end_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('appointments', 'EGN')
    # ### end Alembic commands ###
